language: generic

# required to install tools on Linux
sudo: required

install:
    # install latest release version
    - wget https://github.com/gohugoio/hugo/releases/download/v0.49.2/hugo_0.49.2_Linux-64bit.deb
    - sudo dpkg -i hugo_0.49.2_Linux-64bit.deb

script:
    - hugo

deploy:
  provider: pages
  repo: abhinayagarwal/hugo-site-public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: false
  local-dir: public
  target_branch: master